name: Acceptance Tests
on:
  push:
    paths-ignore:
      - 'LICENSE'
      - '**.md'
      - 'website/**'
      - 'docs/**'
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2.1.3
      with:
        go-version: '1.16'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2.3.4

    - name: Get dependencies
      run: |
        go mod download
    - name: Build
      run: |
        go build -v .
  test:
    name: Matrix Test
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 240
    strategy:
      fail-fast: false
      matrix:
        version:
          - stable
        terraform:
          - '1.1.5'
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2.1.3
      with:
        go-version: '1.16'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2.3.4

    - name: Get dependencies
      run: |
        go mod download

    - name: TF acceptance tests
      timeout-minutes: 180
      env:
        TF_ACC: "1"
        TF_ACC_TERRAFORM_VERSION: ${{ matrix.terraform }}
        # TF_SCHEMA_PANIC_ON_ERROR: "1"
        # TF_LOG: "DEBUG"
        #
        EQUINIX_API_TOKEN: ${{ secrets.EQUINIX_API_TOKEN }}
        METAL_AUTH_TOKEN: ${{ secrets.METAL_AUTH_TOKEN }}
        TEST_ARGS: "-run='Test.*Metal'" #regexp to run just metal tests
      run: |
        go test -v -coverprofile coverage.txt -covermode=atomic -parallel 8 -timeout 180m ${TEST_ARGS} ./...
    - name: Sweeper
      if: ${{ always() }}
      env:
        EQUINIX_API_TOKEN: ${{ secrets.EQUINIX_API_TOKEN }}
        METAL_AUTH_TOKEN: ${{ secrets.METAL_AUTH_TOKEN }}
        SWEEP: "all" #Flag required to define the regions that the sweeper is to be ran in
        SWEEP_ALLOW_FAILURES: "true" #Enable to allow Sweeper Tests to continue after failures
      run: |
        # Added sweep-run to filter Metal test
        go test ./... -v -timeout 180m -sweep=${SWEEP} -sweep-allow-failures=${SWEEP_ALLOW_FAILURES} -sweep-run=$(grep -o 'AddTestSweepers("[^"]*"' equinix/resource_metal_* |cut -d '"' -f2 | paste -s -d, -)
    - name: Upload coverage to Codecov
      if: ${{ always() }}
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.txt
