name: Upgrade provider dependency in Pulumi provider
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
env:
  PULUMI_REPO_OWNER: equinix
  PULUMI_REPO_NAME: pulumi-equinix
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Open new ISSUE on Pulumi provider repository
      uses: GuillaumeFalourd/open-issue-action@v1
      with:
        access-token: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        repo-owner: ${{ env.PULUMI_REPO_OWNER }}
        repo-name: ${{ env.PULUMI_REPO_NAME }}
        issue-title: Upgrade ${{ github.event.repository.name }} to ${{ github.ref_name }}
        issue-body: "Release details: https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}"
